### ISSUE TITLE
Link click ERROR, mp3 (very slow)

### ISSUE THREAD

**Issue by Davide2009** [Maxstupo/ydl-ui#102]
Hello!
If I click on the link under URL it gives me Error "Unmanaged execution in the application", the version is 2.9
https://ibb.co/n6m4kqV
the error comes out if I paste only the end of the link
Paste example: EmGFdalXd-w gives me an error
if I paste the full link:
https://www.youtube.com/watch?v=EmGFdalXd-w
then it works.

Another thing is that it takes forever to download the .mp3, with a .bat it takes me 900% less with the option
Bin\youtube-dl.exe -o Download/%%(title)s.%%(ext)s EmGFdalXd-w -x --audio-format mp3 --audio-quality 0
I believe the default audio selection like the one I listed above is fine, but you can always add a tab only for audio or leave the cbox as it is but improve it .. I did a lot of testing, but I think you download the first video and then convert it back to .mp3 with ffmpeg

**Comment by MatheusOliveira-dev** [comment]
This change only affects the action when the user clicks the download list link to open in browser.

**Comment by Maxstupo** [comment]
> I did a lot of testing, but I think you download the first video and then convert it back to .mp3 with ffmpeg.

Yes. The `Audio Only` option uses `--audio-format` and `--extract-audio` flags (See preview tab when adding a download). I did this since some videos aren't separate audio+video streams. 

You can speed up the download by using a custom format selector while in Advanced mode to only download the audio stream. (e.g. `bestaudio/best`)
