### ISSUE TITLE
YDL-UI 2.6.2 - Proposal for improvements

### ISSUE THREAD

**Issue by bovirus** [Maxstupo/ydl-ui#49]
@Maxstupo 

I have some proposal for improvements

- In the main window reduce the default width for size column (too large)
- In the main window reduce the default width for progress (too large)
- In the main window reduce the default width for speed column (too large)
- In the main window reduce the default width for estimated time column (too large)
- In the main window increase the default width for URL column (too short)
- Add to the main window the colum for info about save folder

- Save the column order/width for next run (now on nexrt run reset to default).

- Set by default save path as folder where YDL-UI is.

- Save the default save path (if you change it) for next run.

- Save settings like video quality/frame rate and preferred/fallback check for next run.

- Is not clear the maeining of enable/dsiabled "Prefered" control box.

**Comment by Maxstupo** [comment]
@bovirus 

>     * In the main window reduce the default width for size column (too large)
>     * In the main window reduce the default width for progress (too large)
>     * In the main window reduce the default width for speed column (too large)
>     * In the main window reduce the default width for estimated time column (too large)
>     * In the main window increase the default width for URL column (too short)
This seems to be a bug introduced in v2.6.2 caused by auto resizing the columns on language change. I will look into fixing this.

v2.6.1
![YDL-UI_Portable_v2 6 1_Columns](https://user-images.githubusercontent.com/6497952/68906652-29267b80-0799-11ea-9acf-cfc9018ddc4e.png)

v2.6.2
![YDL-UI_Portable_v2 6 2_Columns](https://user-images.githubusercontent.com/6497952/68906656-2c216c00-0799-11ea-9d66-68f61bf87b48.png)
<br>

>     * Save the column order/width for next run (now on nexrt run reset to default).
I will look into adding this.
<br>
>     * Add to the main window the colum for info about save folder
Right click on a download > Open download directory.
<br>
>     * Set by default save path as folder where YDL-UI is.
>     * Save the default save path (if you change it) for next run.
You can set the default download directory in `Settings > Download`.
<br>
>     * Save settings like video quality/frame rate and preferred/fallback check for next run.
You can use the `Remember Download Settings` checkbox located in `Settings > Download`, this will remember the previously used settings for the `Add Download` window.
<br>
>     * Is not clear the maeining of enable/dsiabled "Prefered" control box.
If the preferred checkbox for video quality is checked, YDL-UI will download the highest resolution available while not exceeding the resolution you specify. So if you specify 1080p, the highest resolution available up to 1080p will be downloaded.<br>
The same applies for the frame rate preferred checkbox.

**Comment by bovirus** [comment]
@Maxstupo 

About to add file with different location for saving could be useful to have the info about the destination folder in main window.

My request is to set by default in distribution archive

- option "Rember Download settings" enabled
- default download directory set as folder where YDL-UI is

Probably "Preferred" text option could be not so clear.
I will check an alternative for the translation of this option.

**Comment by Maxstupo** [comment]
@bovirus 

I have added a download directory column, and the ability to show/hide columns by right-clicking on the column header (column order and width will be remembered on restart).
![YDL_UI_Portable_Column_Selection](https://user-images.githubusercontent.com/6497952/69217583-1a89fb00-0bc3-11ea-8185-805f7cd856fb.png)


The defaults for `Remember Download Settings` and `Download Directory` are fine the way they are. Using `./` for the default download directory, videos will be saved to the same folder that `YDL-UI.exe` is in.

**Comment by bovirus** [comment]
Thanks. 
I will check translation and if need I will make all changes.

**Comment by Maxstupo** [comment]
@bovirus 

https://github.com/Maxstupo/ydl-ui_i18n/commit/2acba5fe535814f6b54e15663e416aefea1e1ae1

**Comment by bovirus** [comment]
@Maxstupo 

Italian translation changes done.

**Comment by Maxstupo** [comment]
@bovirus 

Release [v2.6.3](https://github.com/Maxstupo/ydl-ui/releases/tag/v2.6.3)
