### ISSUE TITLE
yt-dlc vs youtube-dl

### ISSUE THREAD

**Issue by Fot0n** [Maxstupo/ydl-ui#74]
Hello! You switched back to using youtube-dl. Is this the right solution? Before and after the RIIA attack, the fork showed more activity in development than the original. Now the fate of youtube-dl is not quite obvious (it seems that at the moment PR from the community is [not accepted](https://gitlab.com/dstftw/youtube-dl/-/issues/2) and the author did not speak about his plans). Maybe it's better to use yt-dlc after all?

**Comment by wvxwxvw** [comment]
Which place is more active?
https://gitlab.com/dstftw/youtube-dl/activity
https://github.com/blackjack4494/yt-dlc/actions
yt-dlc is a clone and that says it all.

Well, if you want to use yt-dlc, then use it, no one bothers you.

**Comment by Maxstupo** [comment]
You can potentially use any youtube-dl fork so long as the usage methods are similar to youtube-dl (cmd options and output text). Both youtube-dl and yt-dlc will work. Just replace the `youtube-dl.exe` packaged with ydl-ui with whatever fork/version you want.


The main reason I switched back was because yt-dlc doesn't allow for [updates via -U flag](https://github.com/blackjack4494/yt-dlc/tree/2020.11.11-3#update) and isn't the original.

**Comment by Fot0n** [comment]
> You can potentially use any youtube-dl fork so long as the usage methods are similar to youtube-dl (cmd options and output text). Both youtube-dl and yt-dlc will work. Just replace the youtube-dl.exe packaged with ydl-ui with whatever fork/version you want.

Ok, thanks a lot!
