### ISSUE TITLE
Add --no-mtime flag option

### ISSUE THREAD

**Issue by geoff-B** [Maxstupo/ydl-ui#83]
When I download videos, I usually find them in folders sorted by date modified, so having the `--no-mtime` flag to set it to the current time would be useful. Otherwise, is there an option to use custom flags?

**Comment by Maxstupo** [comment]
Didn't know about that flag. I think it might be worth having that flag enabled always. Doesn't seem like it would have any downsides not having it enabled for every download.

**Comment by geoff-B** [comment]
That would be nice; I have no idea why it's enabled by default for youtube-dl, might be worth asking on their repo.

**Comment by Maxstupo** [comment]
Seems like it has already been discussed https://github.com/ytdl-org/youtube-dl/issues/1709.

**Comment by smaragdus** [comment]
@Maxstupo 

For the time being I will have to use version [2.7.0](https://github.com/Maxstupo/ydl-ui/releases/tag/v2.7.0) since version [2.8.0](https://github.com/Maxstupo/ydl-ui/releases/tag/v2.8.0) does not keep the original date and time set by the server. Is there an option to revert this begaviour? If there is no such option I would like to suggest that you add a new check box, perhaps in **Download** tab in **Settings**:

- Keep the file date and time as set by the server

Or something like that. For me keeping the original date and time of a file is essential and important. Please consider adding such an option as a new check-box (it may be disabled by default).
