### ISSUE TITLE
Different dates for some videos

### ISSUE THREAD

**Issue by MichalSuchy** [Maxstupo/ydl-ui#95]
Hello. When I download videos from Youtube, so some videos have different dates. It is date of change in computer and creation date on Youtube. Dates of change in computer are other, than creation dates on Youtube. Can you correct this issue, please? Thanks, Michal.

**Comment by Maxstupo** [comment]
See `Keep original date and time` option in `Settings > Download`. 

If this doesn't fix the issue, I can't do anything about it, since it's most likely an issue with [youtube-dl](https://github.com/ytdl-org/youtube-dl). Since YDL-UI is just a user interface for [youtube-dl](https://github.com/ytdl-org/youtube-dl).
